#pragma once
#include <stdint.h>

// GENERATED by the panel-canvas repo, tools/gen-scroll-header.mjs, from
// test-vectors/scroll.tsv. Do not edit by hand. Regenerate with
// `npm run gen:vectors`.
//
// These are the same rows the JS renderer asserts against, so a change to the
// scroll geometry in either language fails a test in both. The C++ side is the
// reference implementation: it is what runs on the panel.

struct ScrollVector {
  uint16_t textW;
  uint16_t boxW;
  uint32_t elapsedMs;
  uint16_t scrollMs;
  uint8_t  mode;
  int16_t  offsetX;
  bool     done;
};

static const ScrollVector SCROLL_VECTORS[] = {
  { 40, 62, 100000UL, 40, 2, 0, true },
  { 62, 62, 100000UL, 40, 1, 0, true },
  { 200, 62, 100000UL, 40, 0, 0, true },
  { 100, 62, 0UL, 40, 1, 0, false },
  { 100, 62, 40UL, 40, 1, -1, false },
  { 100, 62, 200UL, 40, 1, -5, false },
  { 100, 62, 1520UL, 40, 1, -38, false },
  { 100, 62, 1720UL, 40, 1, -38, false },
  { 100, 62, 2520UL, 40, 1, 0, true },
  { 100, 62, 9999999UL, 40, 1, 0, true },
  { 100, 62, 1520UL, 40, 2, -38, false },
  { 100, 62, 2240UL, 40, 2, -20, false },
  { 100, 62, 3040UL, 40, 2, 0, false },
  { 100, 62, 9999999UL, 40, 2, -35, false },
  { 100, 62, 10UL, 0, 1, -10, false },
  { 100, 0, 400UL, 40, 1, -10, false },
  { 0, 62, 400UL, 40, 1, 0, true },
};

static const unsigned SCROLL_VECTOR_COUNT = sizeof(SCROLL_VECTORS) / sizeof(SCROLL_VECTORS[0]);
